# Use Ubuntu 20.04 as base image
FROM ubuntu:20.04
# Set the working directory
WORKDIR /var/www/html
RUN chmod -R 777 /var/www/html
COPY . /var/www/html

# Update and install necessary packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    nginx \
    php-fpm \
    php-cli \
    php-mbstring \
    php-xml \
    nodejs \
    npm \
    python3 \
    python3-pip \
    curl \
    nano && \
    npm install -g vue && \
    apt-get install -y yarn && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
apt-get update && \
apt-get install nodejs -y


# Install Python dependencies from requirements.txt
RUN pip3 install -r /var/www/html/python/requirements.txt


# Install Composer for PHP (optional)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy Nginx configuration file
COPY ./default /etc/nginx/sites-enabled/default

# Copy application files to appropriate directories
COPY laravel /var/www/html/laravel
COPY vue/myapp /var/www/html/vue
COPY node /var/www/html/node
COPY python /var/www/html/python

# Expose port 80
EXPOSE 80

# Start Nginx and other services
#CMD service php7.4-fpm start && nginx -g "daemon off;"


CMD ["sh", "-c", "service php7.4-fpm start & cd /var/www/html/node & npm install & node /var/www/html/node/index.js & python3 /var/www/html/python/app.py &  cd /var/www/html/vue/myapp & npm install & npm run serve  & nginx -g 'daemon off;'"]
#CMD ["sh", "-c", "service php7.4-fpm start & cd /var/www/html/node & npm install & node /var/www/html/node/index.js & python3 /var/www/html/python/app.py &  cd /var/www/html/vue/myapp & npm install & npm run serve & npm run build  & nginx -g 'daemon off;'"]

#CMD service php7.4-fpm start & \
 #   cd /var/www/html/node & npm install & node /var/www/html/node/index.js & \
  #  python3 /var/www/html/python/app.py & \
   # cd /var/www/html/vue/myapp & npm install & npm run serve & \
    #nginx -g 'daemon off;'
