version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  multi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - ./php:/var/www/html/php
      - ./vue:/var/www/html/vue
      - ./node:/var/www/html/node
      - ./python:/var/www/html/python

volumes:
  postgres-data:
  mongodb-data:
